# 模型参数
vocab_size: 10001
context_length: 256
d_model: 512
num_layers: 4
num_heads: 16
d_ff: 1344
rope_theta: 10000.0

# 优化器
betas: [0.9,0.95]
eps: 1.0e-8
weight_decay: 0.01

# 学习率调度器
max_lr : 6.0e-4
min_lr : 6.0e-5
warmup_ratio : 0.01
cosine_cycle_ratio: 1


# tokenizer
vocab_file_path: /home/liuxiaoming/clx/data/trained/tokenizer/vocab_size_10000/vocab_tinystories.json
merges_file_path: /home/liuxiaoming/clx/data/trained/tokenizer/vocab_size_10000/merges_tinystories.json

# 训练
enable_wandb: yes
wandb_project_name: cs336
wandb_run_name: TinyStories验证集训练过拟合测试
enable_eval: no
train_path: /home/liuxiaoming/clx/data/tokenized_output/TinyStoriesV2-GPT4-valid.bin
eval_path: /home/liuxiaoming/clx/data/tokenized_output/TinyStoriesV2-GPT4-valid.bin
batch_size: 16
num_epoch: 10
log_iter: 1000
seed: 42
save_dir: /data/clx/pycharm_projs/assignment1-basics/assignment1-basics/save
save_iter: 6000 # 每隔多少步保存一次

# 梯度裁剪
max_l2_norm: 1.0